# Sample deployment file, used to run Machine Controller Manager on your cluster

apiVersion: apps/v1beta1 # Version may change based on kubernetes version
kind: Deployment
metadata:
  name: machine-controller-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: machine-controller-manager
    spec:
      containers:
      - name: machine-controller-manager
        image: registry.f-i-ts.io/gardener-project/gardener/machine-controller-manager:0.18.0
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - ./machine-controller-manager
          - --v=2
          - --target-kubeconfig=$(TARGET_KUBECONFIG) # Mandatory Parameter - Filepath to the target cluster's kubeconfig where node objects are expected to join.
          - --control-kubeconfig=$(CONTROL_KUBECONFIG) # Optional Parameter - Default value is same as target-kubeconfig - Filepath to the control cluster's kubeconfig where machine objects would be created. Optionally you could also use "inClusterConfig" when pod is running inside control kubeconfig.
          - --namespace=$(CONTROL_NAMESPACE) # Optional Parameter - Default value for namespace is 'default' - The control namespace where the controller watches for it's machine objects.
          - --safety-up=2
          - --safety-down=1
          - --machine-creation-timeout=20m
          - --machine-drain-timeout=5m
          - --machine-health-timeout=10m
          - --machine-safety-apiserver-statuscheck-timeout=30s
          - --machine-safety-apiserver-statuscheck-period=1m
          - --machine-safety-orphan-vms-period=30m
          - --machine-safety-overshooting-period=1m
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10258
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
