# Sample secret for Metal

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: ""
  metalAPIKey: Z2VoZWltCg== # metal API key (base64 encoded)
type: Opaque
