# Sample secret for Metal

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # metal cloud config file (base64 encoded)
  metalAPIKey: "{...}" # packet API key (base64 encoded)
type: Opaque
